ezplatform_page_fieldtype:
    layouts:
        '1':
            identifier: '1'
            name: '1 Zone, 1 Column'
            description: 'One zone in one column'
            thumbnail: '/assets/images/page_builder/layouts/1.png'
            template: '@ezdesign/layouts/1.html.twig'
            zones:
                first:
                    name: 'First zone'

        '1_2':
            identifier: '1_2'
            name: '2 Zone, 2 Column'
            description: 'Two zones in columns, narrow left, wide right'
            thumbnail: '/assets/images/page_builder/layouts/1_2.png'
            template: '@ezdesign/layouts/1_2.html.twig'
            zones:
                first:
                    name: 'First zone'
                second:
                    name: 'Second zone'

        '1_2__1':
            identifier: '1_2__1'
            name: '3 Zone, 2+1 Column'
            description: 'Three zones, two columns, narrow left, wide right in first row and one row'
            thumbnail: '/assets/images/page_builder/layouts/1_2__1.png'
            template: '@ezdesign/layouts/1_2__1.html.twig'
            zones:
                first:
                    name: 'First zone'
                second:
                    name: 'Second zone'
                third:
                    name: 'Third zone'

        '2_1':
            identifier: '2_1'
            name: '2 Zone, 2 Column'
            description: 'Two zones in columns, wide left, narrow right'
            thumbnail: '/assets/images/page_builder/layouts/2_1.png'
            template: '@ezdesign/layouts/2_1.html.twig'
            zones:
                first:
                    name: 'First zone'
                second:
                    name: 'Second zone'

        '2_1__1':
            identifier: '2_1__1'
            name: '3 Zone, 2+1 Column'
            description: 'Three zones, two columns, wide left, narrow right in first row and one row'
            thumbnail: '/assets/images/page_builder/layouts/2_1__1.png'
            template: '@ezdesign/layouts/2_1__1.html.twig'
            zones:
                first:
                    name: 'First zone'
                second:
                    name: 'Second zone'
                third:
                    name: 'Third zone'

        '1w__1__1w':
            identifier: '1w__1__1w'
            name: '3 Zone, 1 Column'
            description: 'Three zones, one column, two wide zones'
            thumbnail: '/assets/images/page_builder/layouts/1w__1__1w.png'
            template: '@ezdesign/layouts/1w__1__1w.html.twig'
            zones:
                first:
                    name: 'First wide zone'
                second:
                    name: 'Second zone'
                third:
                    name: 'Third wide zone'

        '1w__2_1__2_1__1w':
            identifier: '1w__2_1__2_1__1w'
            name: '6 Zones, mixed columns'
            description: '6 Zones, mixed columns'
            thumbnail: '/assets/images/page_builder/layouts/1w__1__1w.png'
            template: '@ezdesign/layouts/1w__2_1__2_1__1w.html.twig'
            zones:
                top:
                    name: 'Top wide zone'
                topleft:
                    name: 'Top left inner grid zone'
                topright:
                    name: 'Top right inner grid zone'
                bottomleft:
                    name: 'Bottom left inner grid zone'
                bottomright:
                    name: 'Bottom right inner grid zone'
                bottom:
                    name: 'Bottom wide zone'

    blocks:
        hero:
            views:
                default:
                    template: '@ezdesign/blocks/hero/default.html.twig'
                    name: 'Hero'

        contentlist:
            views:
                blog:
                    template: '@ezdesign/blocks/contentlist/blog.html.twig'
                    name: 'Blog list'

                cards:
                    template: '@ezdesign/blocks/contentlist/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/contentlist/list.html.twig'
                    name: 'List'
        banner:
            views:
                banner:
                    template: '@ezdesign/blocks/banner/banner.html.twig'
                    name: 'Banner'

        embed:
            views:
                embed:
                    template: '@ezdesign/blocks/embed/embed.html.twig'
                    name: 'Hero'

                embed_wide:
                    template: '@ezdesign/blocks/embed/embed_wide.html.twig'
                    name: 'Wide'

        places:
            views:
                map:
                    template: '@ezdesign/blocks/places/map.html.twig'
                    name: 'Map'

                cards:
                    template: '@ezdesign/blocks/places/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/places/list.html.twig'
                    name: 'List'
        tastes:
            views:
                cards:
                    template: '@ezdesign/blocks/tastes/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/tastes/list.html.twig'
                    name: 'List'

                home:
                    template: '@ezdesign/blocks/tastes/home.html.twig'
                    name: 'Home page layout - tastes list'

        gallery:
            views:
                gallery:
                    template: '@ezdesign/blocks/gallery/gallery.html.twig'
                    name: 'Gallery'

        rss:
            views:
                list:
                    template: '@ezdesign/blocks/rss/list.html.twig'
                    name: 'List'

        video:
            views:
                player:
                    template: '@ezdesign/blocks/video/player.html.twig'
                    name: 'Player'

        collection:
            views:
                list:
                    template: '@ezdesign/blocks/collection/list.html.twig'
                    name: 'List'
                    options:
                        match: [article, blog_post, image, product, place]

                cards:
                    template: '@ezdesign/blocks/collection/cards.html.twig'
                    name: 'Cards'
                    options:
                        match: [article, blog_post, image, product, place]

        schedule:
            views:
                cards:
                    template: '@ezdesign/blocks/schedule/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/schedule/list.html.twig'
                    name: 'List'
